# Generated by Django 3.0.4 on 2020-03-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwward', '0002_project_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_content',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='total_design',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='total_usability',
            field=models.FloatField(default=0),
        ),
    ]
